import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { useForm } from "react-hook-form";
import { ISignUp } from "@/server/validation/auth";

type Challenge = {
  id: number;
  title: string;
  image: string;
  description: string;
  category: string;
  location: Location;
  difficulty: number;
  defaultScore: number;
};

type Location = {
  id: number;
  name: string;
  latitude: number;
  longitude: number;
  address: string;
};

export default function Challenges() {
  const challengeRes = api.challenge.getChallenges.useQuery({});
  const chalRes = api.challenge.getChallenge.useQuery({
    id: "cljiyfc0x0000c60w1s5af9d3",
  });

  const challenges = challengeRes.isSuccess && challengeRes.data.challenges;
  const chal = chalRes.isSuccess && chalRes.data.challenge;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex flex-col items-center justify-center">
          <h1 className="text-4xl font-bold text-white">Challenges</h1>
          <div className="flex flex-col items-center justify-center">
            {challengeRes.isSuccess &&
              challenges.map((challenge) => (
                <p>
                  {challenge.title} - {challenge.category}
                </p>
              ))}
          </div>
        </div>
      </main>
    </>
  );
}
